CREATE TABLE SCHOOLS(
schoolID INT(11) NOT NULL AUTO_INCREMENT,
name CHAR(50) NOT NULL UNIQUE,
location CHAR(100) NOT NULL UNIQUE,
description TEXT(1000),
numStudents INT(100) NOT NULL,
PRIMARY KEY (schoolID)
);


CREATE TABLE USERS(
userID INT(11) NOT NULL AUTO_INCREMENT,
fname CHAR(50) NOT NULL,
lname CHAR(50) NOT NULL,
email CHAR(50) UNIQUE NOT NULL,
password CHAR(50) NOT NULL,
school INT(11),
PRIMARY KEY (userID),
FOREIGN KEY (school) REFERENCES SCHOOLS(schoolID)
);

	