CREATE TABLE SCHOOLS(
schoolID INT(11) NOT NULL AUTO_INCREMENT,
name CHAR(50) NOT NULL UNIQUE,
location CHAR(100) NOT NULL UNIQUE,
description TEXT(1000),
numStudents INT(100) NOT NULL,
PRIMARY KEY (schoolID)
);


CREATE TABLE USERS(
userID INT(11) NOT NULL AUTO_INCREMENT,
fname CHAR(50) NOT NULL,
lname CHAR(50) NOT NULL,
email CHAR(50) UNIQUE NOT NULL,
password CHAR(50) NOT NULL,
userlevel INT(4) NOT NULL,
school INT(11),
PRIMARY KEY (userID),
FOREIGN KEY (school) REFERENCES SCHOOLS(schoolID)
);

CREATE TABLE RSOS(
rsoID INT(11) NOT NULL AUTO_INCREMENT,
schoolID INT(11) NOT NULL,
adminID INT(11) NOT NULL,
rsoName CHAR(50) NOT NULL UNIQUE,
description TEXT(1000),
numMembers INT(11) NOT NULL,
PRIMARY KEY(rsoID),
FOREIGN KEY (schoolID) REFERENCES SCHOOLS(schoolID),
FOREIGN KEY (adminID) REFERENCES USERS(userID)
);

CREATE TABLE RSOMEMBERS(
relationshipID INT(11) NOT NULL AUTO_INCREMENT,
rsoID INT(11) NOT NULL,
memberID INT(11) NOT NULL,
PRIMARY KEY(relationshipID),
FOREIGN KEY(rsoID) REFERENCES RSOS(rsoID),
FOREIGN KEY(memberID) REFERENCES USERS(userID)
);

CREATE TABLE EVENTS(
eventID INT(11) NOT NULL AUTO_INCREMENT,
mySchool INT(11) NOT NULL,
myCreator INT(11) NOT NULL,
myRSO INT(11) NOT NULL,
eventName CHAR(50) NOT NULL,
eventCategory CHAR(50) NOT NULL,
description TEXT(1000),
startTime CHAR(20) NOT NULL,
startDate CHAR(20) NOT NULL,
location CHAR(20),
phoneNumber CHAR(20),
email CHAR(50),
privacy INT(4),
PRIMARY KEY (eventID),
FOREIGN KEY (myCreator) REFERENCES USERS(userID),
FOREIGN KEY (myRSO) REFERENCES RSOS(rsoID),
FOREIGN KEY (mySchool) REFERENCES SCHOOLS(schoolID)
);


CREATE TABLE COMMENTS(
commentID INT(11) NOT NULL AUTO_INCREMENT,
commenterID INT(11) NOT NULL,
eventID INT(11) NOT NULL,
commentText TEXT(1000) NOT NULL,
PRIMARY KEY(commentID),
FOREIGN KEY(commentID) REFERENCES USERS(userID),
FOREIGN KEY(eventID) REFERENCES EVENTS(eventID)
);